name: test python files

on:
  pull_request:
    branch:
      -main

  jobs:
    run_tests:
      runs_on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    - name: install python to vm
      uses: action/steps-python
    - name: install our requirements
      run: pip install -r requirements.txt
    - name: run tests 
      run: pytest
